services:
  - type: web
    name: modulo-31-agrupamento-weslei
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run mod31_ex2_projeto_AgrupamentoHierarquico.py --server.port $PORT --server.address 0.0.0.0
